Global_Platform:
  DAZN:
    - dazn-api.com
    - dazn.com
    - dazndn.com
    - indazn.com
    - d151l6v8er5bdm.cloudfront.net
    - d1sgwhnao7452x.cloudfront.net
    - dcalivedazn.akamaized.net
    - dcblivedazn.akamaized.net
  Hotstar:
    - hotstar.com
    - hotstarext.com
  DisneyPlus:
    - disney.connections.edge.bamgrid.com
    - disney.api.edge.bamgrid.com
    - disney-plus.net
    - disneyplus.com
    - dssott.com
    - disneynow.com
    - disneystreaming.com
    - cdn.registerdisney.go.com
  Netflix:
    - netflix.com
    - netflix.net
    - nflximg.com
    - nflximg.net
    - nflxvideo.net
    - nflxext.com
    - nflxso.net
  Amazon_Prime_Video:
    - d1v5ir2lpwr8os.cloudfront.net
    - d22qjgkvxw22r6.cloudfront.net
    - d25xi40x97liuc.cloudfront.net
    - d27xxe7juh1us6.cloudfront.net
    - dmqdd6hw24ucf.cloudfront.net
    - aiv-cdn.net
    - aiv-delivery.net
    - amazonvideo.com
    - atv-ext-eu.amazon.com
    - atv-ext-fe.amazon.com
    - atv-ext.amazon.com
    - atv-ps-eu.amazon.co.uk
    - atv-ps-eu.amazon.com
    - atv-ps-fe.amazon.co.jp
    - atv-ps-fe.amazon.com
    - atv-ps.amazon.com
    - primevideo.com
    - pv-cdn.net
    - video.a2z.com
  TVBAnywherePlus:
    - tvbanywhere.com
    - tvbanywhere.com.sg
    - tvb.com
    - tvb.com.au
    - tvbc.com.cn
    - tvbeventpower.com.hk
    - tvbusa.com
    - tvbweekly.com
    - tvmedia.net.au
  Viu:
    - cognito-identity.us-east-1.amazonaws.com
    - d1k2us671qcoau.cloudfront.net
    - d2anahhhmp1ffz.cloudfront.net
    - dfp6rglgjqszk.cloudfront.net
    - d3o7oi00quuwqu.cloudfront.net
    - mobileanalytics.us-east-1.amazonaws.com
    - viu.com
  Steam_Store:
    - steampowered.com
  YouTube:
    - youtube.com
    - youtubei.googleapis.com
  Google_Search:
    - google.com
  Instagram:
    - instagram.com
  iQiyi:
    - 71.am
    - iq.com
    - iqiyi.com
    - iqiyipic.com
    - pps.tv
    - ppsimg.com
    - qiyi.com
    - qiyipic.com
    - qy.net
  Tiktok:
    - byteoversea.com
    - ibytedtos.com
    - ipstatp.com
    - muscdn.com
    - musical.ly
    - tiktok.com
    - tik-tokapi.com
    - tiktokcdn.com
    - tiktokv.com

Taiwan_Media:
  KKTV:
    - kfs.io
    - kktv-theater.kk.stream
    - kkbox.com
    - kkbox.com.tw
    - kktv.com.tw
    - kktv.me
  LiTV:
    - litv.tv
    - litvfreepc.akamaized.net
  MyVideo:
    - cdn.plyr.io
    - myvideo.net.tw
  4GTV:
    - 4gtv.tv
    - 4gtvfreepc-cds.cdn.hinet.net
    - 4gtvfreepcvod-cds.cdn.hinet.net
    - 4gtvpc-cds.cdn.hinet.net
    - 4gtvpcvod-cds.cdn.hinet.net
  LineTV_TW:
    - d3c7rimkq79yfu.cloudfront.net
    - linetv.tw
  Hami_Video:
    - cdn.hinet.net
    - hamivideo.hinet.net
    - scc.ott.hinet.net
  CatchPlayPlus:
    - catchplay.com
    - d2ivmxp5z2ww0n.cloudfront.net
    - ols-ww100-cp.akamaized.net
    - tra-www000-cp.akamaized.net
  HBO_GO_Asia:
    - 44wilhpljf.execute-api.ap-southeast-1.amazonaws.com
    - bcbolthboa-a.akamaihd.net
    - dai3fd1oh325y.cloudfront.net
    - hboasia1-i.akamaihd.net
    - hboasia2-i.akamaihd.net
    - hboasia3-i.akamaihd.net
    - hboasia4-i.akamaihd.net
    - hboasia5-i.akamaihd.net
    - hboasialive.akamaized.net
    - hbogoprod-vod.akamaized.net
    - hbolb.onwardsmg.com
    - hbounify-prod.evergent.com
    - hbogo.co.th
    - hbogoasia.com
    - hbogoasia.hk
    - hbogoasia.id
    - hbogoasia.ph
    - hbogoasia.sg
    - hbogoasia.tw
  Bahamut_Anime:
    - bahamut.com.tw
    - gamer.com.tw
    - gamer-cds.cdn.hinet.net
    - gamer2-cds.cdn.hinet.net
  BiliBili:
    - bilibili.com
  Friday_Video:
    - video.friday.tw

Canada_Media:
  CBC_Gem:
    - cbc.ca
    - cbchd1dynamicads-i.akamaihd.net
    - cbclivedai5-i.akamaihd.net
    - cbcnewshd-f.akamaihd.net
    - cbcrcott-gem-key.akamaized.net
    - cbcrcott-gem.akamaized.net
    - go-mpulse.net
    - theplatform.com
  Crave_TV:
    - crave.ca
    - go-mpulse.net
    - 9c9media.com

Japan_Media:
  NHK_Plus:
    - nhk.jp
    - nhk.or.jp
  DMM:
    - dmm-extension.com
    - dmm.co.jp
    - dmm.com
    - videomarket.jp
    - p-smith.com
    - vmdash-cenc.akamaized.net
    - img.vm-movie.jp
  Abema:
    - abema.io
    - abema.tv
    - ds-linear-abematv.akamaized.net
    - linear-abematv.akamaized.net
    - ds-vod-abematv.akamaized.net
    - vod-abematv.akamaized.net
    - vod-playout-abematv.akamaized.net
    - ameba.jp
    - hayabusa.io
    - bucketeer.jp
    - abema.adx.promo
    - hayabusa.media
    - abema-tv.com
  NicoNico:
    - dmc.nico
    - nicovideo.jp
    - nimg.jp
  Telasa:
    - telasa.jp
    - kddi-video.com
    - videopass.jp
    - d2lmsumy47c8as.cloudfront.net
  Paravi:
    - paravi.jp
  UNEXT:
    - unext.jp
    - nxtv.jp
  Hulu_Japan:
    - happyon.jp
    - hulu.jp
    - prod.hjholdings.tv
    - streaks.jp
    - yb.uncn.jp
    - hjholdings.jp
  TVer:
    - tver.jp
    - edge.api.brightcove.com
    - gorin.jp
    - screens-lab.jp
    - tver.co.jp
    - dogatch.jp
  GYAO:
    - gyao.yahoo.co.jp
  WOWOW:
    - wowow.co.jp

Europe_Media:
  Rakuten_TV:
    - rakuten.tv
  Funimation:
    - funimation.com
  SkyShowTime:
    - skyshowtimeuk.data.adobedc.net
    - skyshowtime.com
    - cssott.com
    - 4ac1dd56e493354be504f063e4ae3440a13c6776.cws.conviva.com
  HBO_Max:
    - max.com
    - cinemax.com
    - forthethrone.com
    - hbo.com
    - hbomax.com
    - hbomaxcdn.com
    - maxgo.com
  EuroSport:
    - europe-fastly-mediashield-live-prod.cdn.h264.io
    - akamai.prod-live.h264.io
    - eurosport-dlvr-ott.akamaized.net
    - eu3-prod-images.disco-api.com
    - eu3-prod.disco-api.com
    - eurosportplayer.com
    - eurosport.com
    - eurosport.fr
    - eurosport.es
    - eurosport.ro
    - eurosport.io
    - eurosport.ru
    - media-shield.live.eurosport.map.fastly.net
    - eurosport-dlvr-ott-vod.akamaized.net
  ViaPlay:
    - i-viaplay-com.akamaized.net
    - viaplay.com
    - viaplay.pl
    - mtg-api.com
  Sky_GO:
    - sky.com
  BritBox:
    - vod-dash-ntham-comm-live.akamaized.net
    - vod-dash-ntham-comm.live.cf.md.bbci.co.uk
    - vod-hls-ntham-comm-live.akamaized.net
    - vod-hls-ntham-comm.live.cf.md.bbci.co.uk
    - britbox.com
    - d2z3p34itxwaj7.cloudfront.net
  ITV_Hub:
    - itvpnpmobile-a.akamaihd.net
    - itv.com
    - itvstatic.com
  Channel_4:
    - channel4.com
  Channel_5:
    - channel5.com
  BBC:
    - aod-dash-uk-live.akamaized.net
    - aod-hls-uk-live.akamaized.net
    - as-dash-uk-live.akamaized.net
    - as-hls-uk-live.akamaized.net
    - vod-dash-uk-live.akamaized.net
    - vod-dash-ww-live.akamaized.net
    - vod-hls-uk-live.akamaized.net
    - vod-sub-uk-live.akamaized.net
    - vod-thumb-uk-live.akamaized.net
    - vod-thumb-ww-live.akamaized.net
    - vs-cmaf-push-uk-live.akamaized.net
    - bbc
    - bbc.co
    - bbc.co.uk
    - bbc.com
    - bbc.in
    - bbc.net.uk
    - bbcchinese.com
    - bbcfmt.hs.llnwd.net
    - bbcfmt.s.llnwi.net
    - bbci.co
    - bbci.co.uk
    - bbcmedia.co.uk
    - bbcpersian.com
    - bbcverticals.com
    - bidi.net.uk
  DiscoveryPlus:
    - content-ause1-ur-discovery1.uplynk.com
    - disco-api.com
    - discoveryplus.com
    - x-default-stgec.uplynk.com
    - discovery.com
    - discoveryplus.co.uk
    - getblueshift.com
    - litix.io
    - mobile-collector.newrelic.com
    - discovery.uplynk.com
  Salto:
    - salto.fr
  CanalPlus:
    - canalplus.com
  Molotov:
    - molotov.tv
  FranceTV:
    - ftven.fr
  Joyn:
    - joyn.de
  Sky_DE:
    - sky.de
    - edge.api.brightcove.com
  ZDF:
    - zdf.de
  Videoland:
    - videoland.com
  NPO:
    - npo.nl
  RaiPlay:
    - mediapolisvod.rai.it
  Amediateka:
    - amediateka.ru
  MEGOGO:
    - megogo.net
    - vcdn.biz
  Sky_CH:
    - sky.ch
    - zahs.tv
  DigiturkPlay:
    - digiturkplay.com
    - dt-int-gurme-hls.mncdn.com
    - dt-live-int.akamaized.net

Hong_Kong_Media:
  Now_E:
    - nowe.com
    - nowestatic.com
  Now_TV:
    - now.com
  Viu_TV:
    - viu.now.com
    - viu.tv
  MyTVSuper:
    - mytvsuper.com
    - mytvsuperlimited.hb.omtrdc.net
    - mytvsuperlimited.sc.omtrdc.net
    - tvb.com
  HBO_GO_Asia:
    - 44wilhpljf.execute-api.ap-southeast-1.amazonaws.com
    - bcbolthboa-a.akamaihd.net
    - dai3fd1oh325y.cloudfront.net
    - hboasia1-i.akamaihd.net
    - hboasia2-i.akamaihd.net
    - hboasia3-i.akamaihd.net
    - hboasia4-i.akamaihd.net
    - hboasia5-i.akamaihd.net
    - hboasialive.akamaized.net
    - hbogoprod-vod.akamaized.net
    - hbolb.onwardsmg.com
    - hbounify-prod.evergent.com
    - hbogo.co.th
    - hbogoasia.com
    - hbogoasia.hk
    - hbogoasia.id
    - hbogoasia.ph
    - hbogoasia.sg
    - hbogoasia.tw
  HOY_TV:
    - hoy.tv
  BiliBili:
    - bilibili.com

Indian_Media:
  DiscoveryPlus:
    - discoveryplus.in
  MXPlayer:
    - mxplayer.in
  Tata_Play:
    - tataplay.com
  Zee5:
    - zee5.com
  Jio_Cinema:
    - content-jiovoot.voot.com

Korean_Media:
  Wavve:
    - wavve.com
    - pooq.co.kr
  Tving:
    - tving.com
  Coupang_Play:
    - coupangplay.com
  Naver_TV:
    - naver.com
    - navercorp.com
    - pstatic.net
    - smartmediarep.com
  Afreeca_TV:
    - afreecatv.com
  KBS_Domestic:
    - kbs.co.kr
  JTBC:
    - jtbc.co.kr

China_Media:
  YouTube:
    - youtube.com
    - youtubei.googleapis.com
  BiliBili:
    - bilibili.com
  Netease_Cloud_Music:
    - music.163.com
    - music.126.net
  iQiyi:
    - 71.am
    - 71.am.com
    - 71edge.com
    - 71edge.net
    - aianno.cn
    - aianno.com
    - aiqiyicloud-mgmt.com
    - aiqiyicloud.com
    - aiqiyicloud.net
    - baiying.com
    - gitv.cn
    - gitv.tv
    - ibkstore.com
    - iq.com
    - iqiyi.com
    - iqiyi.demo.uwp
    - iqiyiedge.com
    - iqiyiedge.net
    - iqiyipic.com
    - jiangbing.cn
    - pps.tv
    - ppsimg.com
    - ppstream.cn
    - ppstream.com
    - ppstream.com.cn
    - ppstream.net
    - ppstream.net.cn
    - ppsurl.com
    - qiyi.cn
    - qiyi.com
    - qiyipic.com
    - qy.com
    - qy.net
    - suike.cn
  Youku:
    - soku.com
    - youku.com
    - ykimg.com
